language: python
cache: pip
matrix:
    include:
        - python: '2.7'
        - python: '3.4'
        - python: '3.5.1'     # Special, it doesn't have typing.Text
          dist: trusty        # needed because xenial doesn't have 3.5.1
        - python: '3.5'       # Latest, e.g. 3.5.4
        - python: '3.6'
          env: USE_MYPY=true
        - python: '3.7'
          dist: xenial        # needed because Python 3.7 is broken on travis CI Trusty
          sudo: true
          env: USE_MYPY=true
        - python: '3.8-dev'
          dist: xenial        # needed because Python 3.8 is broken on travis CI Trusty
          sudo: true
          env: USE_MYPY=true
    allow_failures:
        - python: 3.8-dev
  
install:
    - pip install -r requirements.txt
    - if [[ $USE_MYPY == true ]]; then pip install -U mypy; fi
script:
    - pytest
    - if [[ $USE_MYPY == true ]]; then mypy pyannotate_*; fi
